Using loss: pinball.
Using temporary directory /var/folders/9b/_dhnw9_17kgb24l4cq75nq9h0000gn/T/tmp979fqq36.
gefundener dataset Path: /Users/wiebkezink/Documents/Uni Münster/MA/mock_dataset
Loading /mock_dataset dataset from /Users/wiebkezink/Documents/Uni Münster/MA/mock_dataset.
Computed weighting 10.0-quantile-lower bound: 0.09523809523809523.
Length of train and val splits: 5, 2.
New length of train and val splits: 5, 2.
Using 0 workers.
Loading model - reinit: True | path: None specified.
Using architecture unet.
Encoder output channels: (14, 64, 256, 512, 1024, 2048)
Adjusting SegmentationHead with encoder output channels: 2048
  0%|                                                                                                                   | 0/100 [00:05<?, ?it/s]
mask shape: torch.Size([5, 65536])
out shape: torch.Size([5, 3, 65536])
target shape: torch.Size([5, 65536])
Removed temporary directory /var/folders/9b/_dhnw9_17kgb24l4cq75nq9h0000gn/T/tmp979fqq36.
Traceback (most recent call last):
  File "/Users/wiebkezink/Documents/Uni Münster/MA/Canopy-Height-Prediction/training/main.py", line 109, in <module>
    runner.run()
  File "/Users/wiebkezink/Documents/Uni Münster/MA/Canopy-Height-Prediction/training/runner.py", line 759, in run
    self.train()  # Train the model
  File "/Users/wiebkezink/Documents/Uni Münster/MA/Canopy-Height-Prediction/training/runner.py", line 710, in train
    metric_loss = self.loss_criteria[loss_type](output, y_target)
  File "/Users/wiebkezink/Documents/Uni Münster/MA/Canopy-Height-Prediction/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/wiebkezink/Documents/Uni Münster/MA/Canopy-Height-Prediction/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/wiebkezink/Documents/Uni Münster/MA/Canopy-Height-Prediction/training/losses/shift_l1_loss.py", line 19, in forward
    return self.shift_loss(predictions, labels)
  File "/Users/wiebkezink/Documents/Uni Münster/MA/Canopy-Height-Prediction/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/wiebkezink/Documents/Uni Münster/MA/Canopy-Height-Prediction/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/wiebkezink/Documents/Uni Münster/MA/Canopy-Height-Prediction/training/losses/shift_loss.py", line 65, in forward
    predictions_view = predictions.view(batch, 1, 1, height, width)
RuntimeError: shape '[5, 1, 1, 256, 256]' is invalid for input of size 983040
